# Generated by Django 3.2.9 on 2021-11-10 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_auto_20211106_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='planned_end_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
